version: '3'
services:
    web:
        image: nginx:1.19
        ports:
            - "81:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        container_name: pompy_web
    php:
        build:
            context: .
            dockerfile: PHP.DOCKERFILE
        volumes:
            - ./app:/app
        container_name: pompy_php
    mysql:
        image: mariadb:10.7.3
        environment:
            MYSQL_ROOT_PASSWORD: 'admin'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'admin'
            MYSQL_DATABASE: 'mydb'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        container_name: pompy_mysql
volumes:
    mysqldata: {}
